apiVersion: v1
kind: Service
metadata:
  name: employee-reviews-service
  namespace: dealer
spec:
  selector:
    app: employee-reviews-service
  ports:
    - name: grpc
      port: 50063
      targetPort: 50063
    - name: http
      port: 8096
      targetPort: 8096
