// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: brands/v1/brands.proto

package brandsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Brand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Brand) Reset() {
	*x = Brand{}
	mi := &file_brands_v1_brands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Brand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brand) ProtoMessage() {}

func (x *Brand) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brand.ProtoReflect.Descriptor instead.
func (*Brand) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{0}
}

func (x *Brand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Brand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Brand) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Brand) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrandRequest) Reset() {
	*x = CreateBrandRequest{}
	mi := &file_brands_v1_brands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrandRequest) ProtoMessage() {}

func (x *CreateBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrandRequest.ProtoReflect.Descriptor instead.
func (*CreateBrandRequest) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         *Brand                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrandResponse) Reset() {
	*x = CreateBrandResponse{}
	mi := &file_brands_v1_brands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrandResponse) ProtoMessage() {}

func (x *CreateBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrandResponse.ProtoReflect.Descriptor instead.
func (*CreateBrandResponse) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBrandResponse) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

type GetBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandRequest) Reset() {
	*x = GetBrandRequest{}
	mi := &file_brands_v1_brands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandRequest) ProtoMessage() {}

func (x *GetBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandRequest.ProtoReflect.Descriptor instead.
func (*GetBrandRequest) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{3}
}

func (x *GetBrandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         *Brand                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandResponse) Reset() {
	*x = GetBrandResponse{}
	mi := &file_brands_v1_brands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandResponse) ProtoMessage() {}

func (x *GetBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandResponse.ProtoReflect.Descriptor instead.
func (*GetBrandResponse) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{4}
}

func (x *GetBrandResponse) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

type ListBrandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBrandsRequest) Reset() {
	*x = ListBrandsRequest{}
	mi := &file_brands_v1_brands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandsRequest) ProtoMessage() {}

func (x *ListBrandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandsRequest.ProtoReflect.Descriptor instead.
func (*ListBrandsRequest) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{5}
}

func (x *ListBrandsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBrandsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListBrandsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListBrandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brands        []*Brand               `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBrandsResponse) Reset() {
	*x = ListBrandsResponse{}
	mi := &file_brands_v1_brands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandsResponse) ProtoMessage() {}

func (x *ListBrandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandsResponse.ProtoReflect.Descriptor instead.
func (*ListBrandsResponse) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{6}
}

func (x *ListBrandsResponse) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *ListBrandsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBrandRequest) Reset() {
	*x = UpdateBrandRequest{}
	mi := &file_brands_v1_brands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBrandRequest) ProtoMessage() {}

func (x *UpdateBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBrandRequest.ProtoReflect.Descriptor instead.
func (*UpdateBrandRequest) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBrandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBrandRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type UpdateBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         *Brand                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBrandResponse) Reset() {
	*x = UpdateBrandResponse{}
	mi := &file_brands_v1_brands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBrandResponse) ProtoMessage() {}

func (x *UpdateBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBrandResponse.ProtoReflect.Descriptor instead.
func (*UpdateBrandResponse) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBrandResponse) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

type DeleteBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBrandRequest) Reset() {
	*x = DeleteBrandRequest{}
	mi := &file_brands_v1_brands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBrandRequest) ProtoMessage() {}

func (x *DeleteBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBrandRequest.ProtoReflect.Descriptor instead.
func (*DeleteBrandRequest) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBrandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBrandResponse) Reset() {
	*x = DeleteBrandResponse{}
	mi := &file_brands_v1_brands_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBrandResponse) ProtoMessage() {}

func (x *DeleteBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brands_v1_brands_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBrandResponse.ProtoReflect.Descriptor instead.
func (*DeleteBrandResponse) Descriptor() ([]byte, []int) {
	return file_brands_v1_brands_proto_rawDescGZIP(), []int{10}
}

var File_brands_v1_brands_proto protoreflect.FileDescriptor

const file_brands_v1_brands_proto_rawDesc = "" +
	"\n" +
	"\x16brands/v1/brands.proto\x12\tbrands.v1\"i\n" +
	"\x05Brand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"(\n" +
	"\x12CreateBrandRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"=\n" +
	"\x13CreateBrandResponse\x12&\n" +
	"\x05brand\x18\x01 \x01(\v2\x10.brands.v1.BrandR\x05brand\"!\n" +
	"\x0fGetBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x10GetBrandResponse\x12&\n" +
	"\x05brand\x18\x01 \x01(\v2\x10.brands.v1.BrandR\x05brand\"Y\n" +
	"\x11ListBrandsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"T\n" +
	"\x12ListBrandsResponse\x12(\n" +
	"\x06brands\x18\x01 \x03(\v2\x10.brands.v1.BrandR\x06brands\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"F\n" +
	"\x12UpdateBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"=\n" +
	"\x13UpdateBrandResponse\x12&\n" +
	"\x05brand\x18\x01 \x01(\v2\x10.brands.v1.BrandR\x05brand\"$\n" +
	"\x12DeleteBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteBrandResponse2\x89\x03\n" +
	"\rBrandsService\x12L\n" +
	"\vCreateBrand\x12\x1d.brands.v1.CreateBrandRequest\x1a\x1e.brands.v1.CreateBrandResponse\x12C\n" +
	"\bGetBrand\x12\x1a.brands.v1.GetBrandRequest\x1a\x1b.brands.v1.GetBrandResponse\x12I\n" +
	"\n" +
	"ListBrands\x12\x1c.brands.v1.ListBrandsRequest\x1a\x1d.brands.v1.ListBrandsResponse\x12L\n" +
	"\vUpdateBrand\x12\x1d.brands.v1.UpdateBrandRequest\x1a\x1e.brands.v1.UpdateBrandResponse\x12L\n" +
	"\vDeleteBrand\x12\x1d.brands.v1.DeleteBrandRequest\x1a\x1e.brands.v1.DeleteBrandResponseB4Z2github.com/dealer/dealer/pkg/pb/brands/v1;brandsv1b\x06proto3"

var (
	file_brands_v1_brands_proto_rawDescOnce sync.Once
	file_brands_v1_brands_proto_rawDescData []byte
)

func file_brands_v1_brands_proto_rawDescGZIP() []byte {
	file_brands_v1_brands_proto_rawDescOnce.Do(func() {
		file_brands_v1_brands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brands_v1_brands_proto_rawDesc), len(file_brands_v1_brands_proto_rawDesc)))
	})
	return file_brands_v1_brands_proto_rawDescData
}

var file_brands_v1_brands_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_brands_v1_brands_proto_goTypes = []any{
	(*Brand)(nil),               // 0: brands.v1.Brand
	(*CreateBrandRequest)(nil),  // 1: brands.v1.CreateBrandRequest
	(*CreateBrandResponse)(nil), // 2: brands.v1.CreateBrandResponse
	(*GetBrandRequest)(nil),     // 3: brands.v1.GetBrandRequest
	(*GetBrandResponse)(nil),    // 4: brands.v1.GetBrandResponse
	(*ListBrandsRequest)(nil),   // 5: brands.v1.ListBrandsRequest
	(*ListBrandsResponse)(nil),  // 6: brands.v1.ListBrandsResponse
	(*UpdateBrandRequest)(nil),  // 7: brands.v1.UpdateBrandRequest
	(*UpdateBrandResponse)(nil), // 8: brands.v1.UpdateBrandResponse
	(*DeleteBrandRequest)(nil),  // 9: brands.v1.DeleteBrandRequest
	(*DeleteBrandResponse)(nil), // 10: brands.v1.DeleteBrandResponse
}
var file_brands_v1_brands_proto_depIdxs = []int32{
	0,  // 0: brands.v1.CreateBrandResponse.brand:type_name -> brands.v1.Brand
	0,  // 1: brands.v1.GetBrandResponse.brand:type_name -> brands.v1.Brand
	0,  // 2: brands.v1.ListBrandsResponse.brands:type_name -> brands.v1.Brand
	0,  // 3: brands.v1.UpdateBrandResponse.brand:type_name -> brands.v1.Brand
	1,  // 4: brands.v1.BrandsService.CreateBrand:input_type -> brands.v1.CreateBrandRequest
	3,  // 5: brands.v1.BrandsService.GetBrand:input_type -> brands.v1.GetBrandRequest
	5,  // 6: brands.v1.BrandsService.ListBrands:input_type -> brands.v1.ListBrandsRequest
	7,  // 7: brands.v1.BrandsService.UpdateBrand:input_type -> brands.v1.UpdateBrandRequest
	9,  // 8: brands.v1.BrandsService.DeleteBrand:input_type -> brands.v1.DeleteBrandRequest
	2,  // 9: brands.v1.BrandsService.CreateBrand:output_type -> brands.v1.CreateBrandResponse
	4,  // 10: brands.v1.BrandsService.GetBrand:output_type -> brands.v1.GetBrandResponse
	6,  // 11: brands.v1.BrandsService.ListBrands:output_type -> brands.v1.ListBrandsResponse
	8,  // 12: brands.v1.BrandsService.UpdateBrand:output_type -> brands.v1.UpdateBrandResponse
	10, // 13: brands.v1.BrandsService.DeleteBrand:output_type -> brands.v1.DeleteBrandResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_brands_v1_brands_proto_init() }
func file_brands_v1_brands_proto_init() {
	if File_brands_v1_brands_proto != nil {
		return
	}
	file_brands_v1_brands_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brands_v1_brands_proto_rawDesc), len(file_brands_v1_brands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brands_v1_brands_proto_goTypes,
		DependencyIndexes: file_brands_v1_brands_proto_depIdxs,
		MessageInfos:      file_brands_v1_brands_proto_msgTypes,
	}.Build()
	File_brands_v1_brands_proto = out.File
	file_brands_v1_brands_proto_goTypes = nil
	file_brands_v1_brands_proto_depIdxs = nil
}
