// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: statistics/client/v1/client_stats.proto

package clientstatsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientStatisticsService_GetOverview_FullMethodName = "/statistics.client.v1.ClientStatisticsService/GetOverview"
)

// ClientStatisticsServiceClient is the client API for ClientStatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сводная статистика по клиентской зоне (employee gateway).
type ClientStatisticsServiceClient interface {
	GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*GetOverviewResponse, error)
}

type clientStatisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientStatisticsServiceClient(cc grpc.ClientConnInterface) ClientStatisticsServiceClient {
	return &clientStatisticsServiceClient{cc}
}

func (c *clientStatisticsServiceClient) GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*GetOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOverviewResponse)
	err := c.cc.Invoke(ctx, ClientStatisticsService_GetOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientStatisticsServiceServer is the server API for ClientStatisticsService service.
// All implementations must embed UnimplementedClientStatisticsServiceServer
// for forward compatibility.
//
// Сводная статистика по клиентской зоне (employee gateway).
type ClientStatisticsServiceServer interface {
	GetOverview(context.Context, *GetOverviewRequest) (*GetOverviewResponse, error)
	mustEmbedUnimplementedClientStatisticsServiceServer()
}

// UnimplementedClientStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientStatisticsServiceServer struct{}

func (UnimplementedClientStatisticsServiceServer) GetOverview(context.Context, *GetOverviewRequest) (*GetOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverview not implemented")
}
func (UnimplementedClientStatisticsServiceServer) mustEmbedUnimplementedClientStatisticsServiceServer() {
}
func (UnimplementedClientStatisticsServiceServer) testEmbeddedByValue() {}

// UnsafeClientStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientStatisticsServiceServer will
// result in compilation errors.
type UnsafeClientStatisticsServiceServer interface {
	mustEmbedUnimplementedClientStatisticsServiceServer()
}

func RegisterClientStatisticsServiceServer(s grpc.ServiceRegistrar, srv ClientStatisticsServiceServer) {
	// If the following call panics, it indicates UnimplementedClientStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientStatisticsService_ServiceDesc, srv)
}

func _ClientStatisticsService_GetOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientStatisticsServiceServer).GetOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientStatisticsService_GetOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientStatisticsServiceServer).GetOverview(ctx, req.(*GetOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientStatisticsService_ServiceDesc is the grpc.ServiceDesc for ClientStatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientStatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.client.v1.ClientStatisticsService",
	HandlerType: (*ClientStatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOverview",
			Handler:    _ClientStatisticsService_GetOverview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistics/client/v1/client_stats.proto",
}
