// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: statistics/client/v1/client_stats.proto

package clientstatsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewStatusCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewStatusCount) Reset() {
	*x = ReviewStatusCount{}
	mi := &file_statistics_client_v1_client_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewStatusCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewStatusCount) ProtoMessage() {}

func (x *ReviewStatusCount) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_client_v1_client_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewStatusCount.ProtoReflect.Descriptor instead.
func (*ReviewStatusCount) Descriptor() ([]byte, []int) {
	return file_statistics_client_v1_client_stats_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewStatusCount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReviewStatusCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClientOverview struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientsCount         int64                  `protobuf:"varint,1,opt,name=clients_count,json=clientsCount,proto3" json:"clients_count,omitempty"`
	ClientVehiclesCount  int64                  `protobuf:"varint,2,opt,name=client_vehicles_count,json=clientVehiclesCount,proto3" json:"client_vehicles_count,omitempty"`
	RegisteredUsersCount int64                  `protobuf:"varint,3,opt,name=registered_users_count,json=registeredUsersCount,proto3" json:"registered_users_count,omitempty"`
	ReviewsCount         int64                  `protobuf:"varint,4,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	AverageRating        float64                `protobuf:"fixed64,5,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	ReviewsByStatus      []*ReviewStatusCount   `protobuf:"bytes,6,rep,name=reviews_by_status,json=reviewsByStatus,proto3" json:"reviews_by_status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClientOverview) Reset() {
	*x = ClientOverview{}
	mi := &file_statistics_client_v1_client_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOverview) ProtoMessage() {}

func (x *ClientOverview) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_client_v1_client_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOverview.ProtoReflect.Descriptor instead.
func (*ClientOverview) Descriptor() ([]byte, []int) {
	return file_statistics_client_v1_client_stats_proto_rawDescGZIP(), []int{1}
}

func (x *ClientOverview) GetClientsCount() int64 {
	if x != nil {
		return x.ClientsCount
	}
	return 0
}

func (x *ClientOverview) GetClientVehiclesCount() int64 {
	if x != nil {
		return x.ClientVehiclesCount
	}
	return 0
}

func (x *ClientOverview) GetRegisteredUsersCount() int64 {
	if x != nil {
		return x.RegisteredUsersCount
	}
	return 0
}

func (x *ClientOverview) GetReviewsCount() int64 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

func (x *ClientOverview) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *ClientOverview) GetReviewsByStatus() []*ReviewStatusCount {
	if x != nil {
		return x.ReviewsByStatus
	}
	return nil
}

type GetOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewRequest) Reset() {
	*x = GetOverviewRequest{}
	mi := &file_statistics_client_v1_client_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewRequest) ProtoMessage() {}

func (x *GetOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_client_v1_client_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetOverviewRequest) Descriptor() ([]byte, []int) {
	return file_statistics_client_v1_client_stats_proto_rawDescGZIP(), []int{2}
}

type GetOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overview      *ClientOverview        `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewResponse) Reset() {
	*x = GetOverviewResponse{}
	mi := &file_statistics_client_v1_client_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewResponse) ProtoMessage() {}

func (x *GetOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_client_v1_client_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetOverviewResponse) Descriptor() ([]byte, []int) {
	return file_statistics_client_v1_client_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetOverviewResponse) GetOverview() *ClientOverview {
	if x != nil {
		return x.Overview
	}
	return nil
}

var File_statistics_client_v1_client_stats_proto protoreflect.FileDescriptor

const file_statistics_client_v1_client_stats_proto_rawDesc = "" +
	"\n" +
	"'statistics/client/v1/client_stats.proto\x12\x14statistics.client.v1\x1a\x1cgoogle/api/annotations.proto\"A\n" +
	"\x11ReviewStatusCount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xc0\x02\n" +
	"\x0eClientOverview\x12#\n" +
	"\rclients_count\x18\x01 \x01(\x03R\fclientsCount\x122\n" +
	"\x15client_vehicles_count\x18\x02 \x01(\x03R\x13clientVehiclesCount\x124\n" +
	"\x16registered_users_count\x18\x03 \x01(\x03R\x14registeredUsersCount\x12#\n" +
	"\rreviews_count\x18\x04 \x01(\x03R\freviewsCount\x12%\n" +
	"\x0eaverage_rating\x18\x05 \x01(\x01R\raverageRating\x12S\n" +
	"\x11reviews_by_status\x18\x06 \x03(\v2'.statistics.client.v1.ReviewStatusCountR\x0freviewsByStatus\"\x14\n" +
	"\x12GetOverviewRequest\"W\n" +
	"\x13GetOverviewResponse\x12@\n" +
	"\boverview\x18\x01 \x01(\v2$.statistics.client.v1.ClientOverviewR\boverview2\xac\x01\n" +
	"\x17ClientStatisticsService\x12\x90\x01\n" +
	"\vGetOverview\x12(.statistics.client.v1.GetOverviewRequest\x1a).statistics.client.v1.GetOverviewResponse\",\x82\xd3\xe4\x93\x02&b\boverview\x12\x1a/api/stats/client/overviewBDZBgithub.com/dealer/dealer/pkg/pb/statistics/client/v1;clientstatsv1b\x06proto3"

var (
	file_statistics_client_v1_client_stats_proto_rawDescOnce sync.Once
	file_statistics_client_v1_client_stats_proto_rawDescData []byte
)

func file_statistics_client_v1_client_stats_proto_rawDescGZIP() []byte {
	file_statistics_client_v1_client_stats_proto_rawDescOnce.Do(func() {
		file_statistics_client_v1_client_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_client_v1_client_stats_proto_rawDesc), len(file_statistics_client_v1_client_stats_proto_rawDesc)))
	})
	return file_statistics_client_v1_client_stats_proto_rawDescData
}

var file_statistics_client_v1_client_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_statistics_client_v1_client_stats_proto_goTypes = []any{
	(*ReviewStatusCount)(nil),   // 0: statistics.client.v1.ReviewStatusCount
	(*ClientOverview)(nil),      // 1: statistics.client.v1.ClientOverview
	(*GetOverviewRequest)(nil),  // 2: statistics.client.v1.GetOverviewRequest
	(*GetOverviewResponse)(nil), // 3: statistics.client.v1.GetOverviewResponse
}
var file_statistics_client_v1_client_stats_proto_depIdxs = []int32{
	0, // 0: statistics.client.v1.ClientOverview.reviews_by_status:type_name -> statistics.client.v1.ReviewStatusCount
	1, // 1: statistics.client.v1.GetOverviewResponse.overview:type_name -> statistics.client.v1.ClientOverview
	2, // 2: statistics.client.v1.ClientStatisticsService.GetOverview:input_type -> statistics.client.v1.GetOverviewRequest
	3, // 3: statistics.client.v1.ClientStatisticsService.GetOverview:output_type -> statistics.client.v1.GetOverviewResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_statistics_client_v1_client_stats_proto_init() }
func file_statistics_client_v1_client_stats_proto_init() {
	if File_statistics_client_v1_client_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_client_v1_client_stats_proto_rawDesc), len(file_statistics_client_v1_client_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_client_v1_client_stats_proto_goTypes,
		DependencyIndexes: file_statistics_client_v1_client_stats_proto_depIdxs,
		MessageInfos:      file_statistics_client_v1_client_stats_proto_msgTypes,
	}.Build()
	File_statistics_client_v1_client_stats_proto = out.File
	file_statistics_client_v1_client_stats_proto_goTypes = nil
	file_statistics_client_v1_client_stats_proto_depIdxs = nil
}
