// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: parts/v1/parts.proto

package partsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartsService_CreatePart_FullMethodName                       = "/parts.v1.PartsService/CreatePart"
	PartsService_GetPart_FullMethodName                          = "/parts.v1.PartsService/GetPart"
	PartsService_ListPartStock_FullMethodName                    = "/parts.v1.PartsService/ListPartStock"
	PartsService_ListParts_FullMethodName                        = "/parts.v1.PartsService/ListParts"
	PartsService_UpdatePart_FullMethodName                       = "/parts.v1.PartsService/UpdatePart"
	PartsService_DeletePart_FullMethodName                       = "/parts.v1.PartsService/DeletePart"
	PartsService_CreateFolder_FullMethodName                     = "/parts.v1.PartsService/CreateFolder"
	PartsService_GetFolder_FullMethodName                        = "/parts.v1.PartsService/GetFolder"
	PartsService_ListFolders_FullMethodName                      = "/parts.v1.PartsService/ListFolders"
	PartsService_UpdateFolder_FullMethodName                     = "/parts.v1.PartsService/UpdateFolder"
	PartsService_DeleteFolder_FullMethodName                     = "/parts.v1.PartsService/DeleteFolder"
	PartsService_CreateMovementDocument_FullMethodName           = "/parts.v1.PartsService/CreateMovementDocument"
	PartsService_GetMovementDocument_FullMethodName              = "/parts.v1.PartsService/GetMovementDocument"
	PartsService_UpdateMovementDocument_FullMethodName           = "/parts.v1.PartsService/UpdateMovementDocument"
	PartsService_ListMovementDocuments_FullMethodName            = "/parts.v1.PartsService/ListMovementDocuments"
	PartsService_StartMovementDocument_FullMethodName            = "/parts.v1.PartsService/StartMovementDocument"
	PartsService_CloseMovementDocument_FullMethodName            = "/parts.v1.PartsService/CloseMovementDocument"
	PartsService_ConfirmMovementDocument_FullMethodName          = "/parts.v1.PartsService/ConfirmMovementDocument"
	PartsService_CancelMovementDocument_FullMethodName           = "/parts.v1.PartsService/CancelMovementDocument"
	PartsService_CreateProductionExtraction_FullMethodName       = "/parts.v1.PartsService/CreateProductionExtraction"
	PartsService_ListSuppliers_FullMethodName                    = "/parts.v1.PartsService/ListSuppliers"
	PartsService_CreateSupplierOrder_FullMethodName              = "/parts.v1.PartsService/CreateSupplierOrder"
	PartsService_GetSupplierOrder_FullMethodName                 = "/parts.v1.PartsService/GetSupplierOrder"
	PartsService_UpdateSupplierOrder_FullMethodName              = "/parts.v1.PartsService/UpdateSupplierOrder"
	PartsService_ListSupplierOrders_FullMethodName               = "/parts.v1.PartsService/ListSupplierOrders"
	PartsService_CancelSupplierOrder_FullMethodName              = "/parts.v1.PartsService/CancelSupplierOrder"
	PartsService_CreateReceiptFromSupplierOrder_FullMethodName   = "/parts.v1.PartsService/CreateReceiptFromSupplierOrder"
	PartsService_CreateCustomerOrder_FullMethodName              = "/parts.v1.PartsService/CreateCustomerOrder"
	PartsService_GetCustomerOrder_FullMethodName                 = "/parts.v1.PartsService/GetCustomerOrder"
	PartsService_UpdateCustomerOrder_FullMethodName              = "/parts.v1.PartsService/UpdateCustomerOrder"
	PartsService_ListCustomerOrders_FullMethodName               = "/parts.v1.PartsService/ListCustomerOrders"
	PartsService_CancelCustomerOrder_FullMethodName              = "/parts.v1.PartsService/CancelCustomerOrder"
	PartsService_CreateSaleFromCustomerOrder_FullMethodName      = "/parts.v1.PartsService/CreateSaleFromCustomerOrder"
	PartsService_CreateWorkOrderFromSupplierOrder_FullMethodName = "/parts.v1.PartsService/CreateWorkOrderFromSupplierOrder"
	PartsService_CreateWorkOrderFromCustomerOrder_FullMethodName = "/parts.v1.PartsService/CreateWorkOrderFromCustomerOrder"
	PartsService_FulfillOrderFromWorkOrder_FullMethodName        = "/parts.v1.PartsService/FulfillOrderFromWorkOrder"
)

// PartsServiceClient is the client API for PartsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartsServiceClient interface {
	CreatePart(ctx context.Context, in *CreatePartRequest, opts ...grpc.CallOption) (*CreatePartResponse, error)
	GetPart(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error)
	ListPartStock(ctx context.Context, in *ListPartStockRequest, opts ...grpc.CallOption) (*ListPartStockResponse, error)
	ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (*ListPartsResponse, error)
	UpdatePart(ctx context.Context, in *UpdatePartRequest, opts ...grpc.CallOption) (*UpdatePartResponse, error)
	DeletePart(ctx context.Context, in *DeletePartRequest, opts ...grpc.CallOption) (*DeletePartResponse, error)
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error)
	GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*GetFolderResponse, error)
	ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*ListFoldersResponse, error)
	UpdateFolder(ctx context.Context, in *UpdateFolderRequest, opts ...grpc.CallOption) (*UpdateFolderResponse, error)
	DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error)
	CreateMovementDocument(ctx context.Context, in *CreateMovementDocumentRequest, opts ...grpc.CallOption) (*CreateMovementDocumentResponse, error)
	GetMovementDocument(ctx context.Context, in *GetMovementDocumentRequest, opts ...grpc.CallOption) (*GetMovementDocumentResponse, error)
	UpdateMovementDocument(ctx context.Context, in *UpdateMovementDocumentRequest, opts ...grpc.CallOption) (*UpdateMovementDocumentResponse, error)
	ListMovementDocuments(ctx context.Context, in *ListMovementDocumentsRequest, opts ...grpc.CallOption) (*ListMovementDocumentsResponse, error)
	StartMovementDocument(ctx context.Context, in *StartMovementDocumentRequest, opts ...grpc.CallOption) (*StartMovementDocumentResponse, error)
	CloseMovementDocument(ctx context.Context, in *CloseMovementDocumentRequest, opts ...grpc.CallOption) (*CloseMovementDocumentResponse, error)
	// Устаревший alias: закрывает документ (списание со склада).
	ConfirmMovementDocument(ctx context.Context, in *ConfirmMovementDocumentRequest, opts ...grpc.CallOption) (*ConfirmMovementDocumentResponse, error)
	CancelMovementDocument(ctx context.Context, in *CancelMovementDocumentRequest, opts ...grpc.CallOption) (*CancelMovementDocumentResponse, error)
	CreateProductionExtraction(ctx context.Context, in *CreateProductionExtractionRequest, opts ...grpc.CallOption) (*CreateProductionExtractionResponse, error)
	ListSuppliers(ctx context.Context, in *ListSuppliersRequest, opts ...grpc.CallOption) (*ListSuppliersResponse, error)
	CreateSupplierOrder(ctx context.Context, in *CreateSupplierOrderRequest, opts ...grpc.CallOption) (*CreateSupplierOrderResponse, error)
	GetSupplierOrder(ctx context.Context, in *GetSupplierOrderRequest, opts ...grpc.CallOption) (*GetSupplierOrderResponse, error)
	UpdateSupplierOrder(ctx context.Context, in *UpdateSupplierOrderRequest, opts ...grpc.CallOption) (*UpdateSupplierOrderResponse, error)
	ListSupplierOrders(ctx context.Context, in *ListSupplierOrdersRequest, opts ...grpc.CallOption) (*ListSupplierOrdersResponse, error)
	CancelSupplierOrder(ctx context.Context, in *CancelSupplierOrderRequest, opts ...grpc.CallOption) (*CancelSupplierOrderResponse, error)
	CreateReceiptFromSupplierOrder(ctx context.Context, in *CreateReceiptFromSupplierOrderRequest, opts ...grpc.CallOption) (*CreateReceiptFromSupplierOrderResponse, error)
	CreateCustomerOrder(ctx context.Context, in *CreateCustomerOrderRequest, opts ...grpc.CallOption) (*CreateCustomerOrderResponse, error)
	GetCustomerOrder(ctx context.Context, in *GetCustomerOrderRequest, opts ...grpc.CallOption) (*GetCustomerOrderResponse, error)
	UpdateCustomerOrder(ctx context.Context, in *UpdateCustomerOrderRequest, opts ...grpc.CallOption) (*UpdateCustomerOrderResponse, error)
	ListCustomerOrders(ctx context.Context, in *ListCustomerOrdersRequest, opts ...grpc.CallOption) (*ListCustomerOrdersResponse, error)
	CancelCustomerOrder(ctx context.Context, in *CancelCustomerOrderRequest, opts ...grpc.CallOption) (*CancelCustomerOrderResponse, error)
	CreateSaleFromCustomerOrder(ctx context.Context, in *CreateSaleFromCustomerOrderRequest, opts ...grpc.CallOption) (*CreateSaleFromCustomerOrderResponse, error)
	CreateWorkOrderFromSupplierOrder(ctx context.Context, in *CreateWorkOrderFromSupplierOrderRequest, opts ...grpc.CallOption) (*CreateWorkOrderFromOrderResponse, error)
	CreateWorkOrderFromCustomerOrder(ctx context.Context, in *CreateWorkOrderFromCustomerOrderRequest, opts ...grpc.CallOption) (*CreateWorkOrderFromOrderResponse, error)
	// Вызывается workorders-service при закрытии заказ-наряда, созданного из заказа.
	FulfillOrderFromWorkOrder(ctx context.Context, in *FulfillOrderFromWorkOrderRequest, opts ...grpc.CallOption) (*FulfillOrderFromWorkOrderResponse, error)
}

type partsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartsServiceClient(cc grpc.ClientConnInterface) PartsServiceClient {
	return &partsServiceClient{cc}
}

func (c *partsServiceClient) CreatePart(ctx context.Context, in *CreatePartRequest, opts ...grpc.CallOption) (*CreatePartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePartResponse)
	err := c.cc.Invoke(ctx, PartsService_CreatePart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) GetPart(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartResponse)
	err := c.cc.Invoke(ctx, PartsService_GetPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) ListPartStock(ctx context.Context, in *ListPartStockRequest, opts ...grpc.CallOption) (*ListPartStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartStockResponse)
	err := c.cc.Invoke(ctx, PartsService_ListPartStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (*ListPartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartsResponse)
	err := c.cc.Invoke(ctx, PartsService_ListParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) UpdatePart(ctx context.Context, in *UpdatePartRequest, opts ...grpc.CallOption) (*UpdatePartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePartResponse)
	err := c.cc.Invoke(ctx, PartsService_UpdatePart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) DeletePart(ctx context.Context, in *DeletePartRequest, opts ...grpc.CallOption) (*DeletePartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePartResponse)
	err := c.cc.Invoke(ctx, PartsService_DeletePart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFolderResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*GetFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFolderResponse)
	err := c.cc.Invoke(ctx, PartsService_GetFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*ListFoldersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFoldersResponse)
	err := c.cc.Invoke(ctx, PartsService_ListFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) UpdateFolder(ctx context.Context, in *UpdateFolderRequest, opts ...grpc.CallOption) (*UpdateFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFolderResponse)
	err := c.cc.Invoke(ctx, PartsService_UpdateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFolderResponse)
	err := c.cc.Invoke(ctx, PartsService_DeleteFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateMovementDocument(ctx context.Context, in *CreateMovementDocumentRequest, opts ...grpc.CallOption) (*CreateMovementDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMovementDocumentResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateMovementDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) GetMovementDocument(ctx context.Context, in *GetMovementDocumentRequest, opts ...grpc.CallOption) (*GetMovementDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMovementDocumentResponse)
	err := c.cc.Invoke(ctx, PartsService_GetMovementDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) UpdateMovementDocument(ctx context.Context, in *UpdateMovementDocumentRequest, opts ...grpc.CallOption) (*UpdateMovementDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMovementDocumentResponse)
	err := c.cc.Invoke(ctx, PartsService_UpdateMovementDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) ListMovementDocuments(ctx context.Context, in *ListMovementDocumentsRequest, opts ...grpc.CallOption) (*ListMovementDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMovementDocumentsResponse)
	err := c.cc.Invoke(ctx, PartsService_ListMovementDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) StartMovementDocument(ctx context.Context, in *StartMovementDocumentRequest, opts ...grpc.CallOption) (*StartMovementDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartMovementDocumentResponse)
	err := c.cc.Invoke(ctx, PartsService_StartMovementDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CloseMovementDocument(ctx context.Context, in *CloseMovementDocumentRequest, opts ...grpc.CallOption) (*CloseMovementDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseMovementDocumentResponse)
	err := c.cc.Invoke(ctx, PartsService_CloseMovementDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) ConfirmMovementDocument(ctx context.Context, in *ConfirmMovementDocumentRequest, opts ...grpc.CallOption) (*ConfirmMovementDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmMovementDocumentResponse)
	err := c.cc.Invoke(ctx, PartsService_ConfirmMovementDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CancelMovementDocument(ctx context.Context, in *CancelMovementDocumentRequest, opts ...grpc.CallOption) (*CancelMovementDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMovementDocumentResponse)
	err := c.cc.Invoke(ctx, PartsService_CancelMovementDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateProductionExtraction(ctx context.Context, in *CreateProductionExtractionRequest, opts ...grpc.CallOption) (*CreateProductionExtractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductionExtractionResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateProductionExtraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) ListSuppliers(ctx context.Context, in *ListSuppliersRequest, opts ...grpc.CallOption) (*ListSuppliersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSuppliersResponse)
	err := c.cc.Invoke(ctx, PartsService_ListSuppliers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateSupplierOrder(ctx context.Context, in *CreateSupplierOrderRequest, opts ...grpc.CallOption) (*CreateSupplierOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupplierOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateSupplierOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) GetSupplierOrder(ctx context.Context, in *GetSupplierOrderRequest, opts ...grpc.CallOption) (*GetSupplierOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupplierOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_GetSupplierOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) UpdateSupplierOrder(ctx context.Context, in *UpdateSupplierOrderRequest, opts ...grpc.CallOption) (*UpdateSupplierOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSupplierOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_UpdateSupplierOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) ListSupplierOrders(ctx context.Context, in *ListSupplierOrdersRequest, opts ...grpc.CallOption) (*ListSupplierOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupplierOrdersResponse)
	err := c.cc.Invoke(ctx, PartsService_ListSupplierOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CancelSupplierOrder(ctx context.Context, in *CancelSupplierOrderRequest, opts ...grpc.CallOption) (*CancelSupplierOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelSupplierOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_CancelSupplierOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateReceiptFromSupplierOrder(ctx context.Context, in *CreateReceiptFromSupplierOrderRequest, opts ...grpc.CallOption) (*CreateReceiptFromSupplierOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReceiptFromSupplierOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateReceiptFromSupplierOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateCustomerOrder(ctx context.Context, in *CreateCustomerOrderRequest, opts ...grpc.CallOption) (*CreateCustomerOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCustomerOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateCustomerOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) GetCustomerOrder(ctx context.Context, in *GetCustomerOrderRequest, opts ...grpc.CallOption) (*GetCustomerOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_GetCustomerOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) UpdateCustomerOrder(ctx context.Context, in *UpdateCustomerOrderRequest, opts ...grpc.CallOption) (*UpdateCustomerOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCustomerOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_UpdateCustomerOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) ListCustomerOrders(ctx context.Context, in *ListCustomerOrdersRequest, opts ...grpc.CallOption) (*ListCustomerOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCustomerOrdersResponse)
	err := c.cc.Invoke(ctx, PartsService_ListCustomerOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CancelCustomerOrder(ctx context.Context, in *CancelCustomerOrderRequest, opts ...grpc.CallOption) (*CancelCustomerOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelCustomerOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_CancelCustomerOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateSaleFromCustomerOrder(ctx context.Context, in *CreateSaleFromCustomerOrderRequest, opts ...grpc.CallOption) (*CreateSaleFromCustomerOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSaleFromCustomerOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateSaleFromCustomerOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateWorkOrderFromSupplierOrder(ctx context.Context, in *CreateWorkOrderFromSupplierOrderRequest, opts ...grpc.CallOption) (*CreateWorkOrderFromOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkOrderFromOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateWorkOrderFromSupplierOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) CreateWorkOrderFromCustomerOrder(ctx context.Context, in *CreateWorkOrderFromCustomerOrderRequest, opts ...grpc.CallOption) (*CreateWorkOrderFromOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkOrderFromOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_CreateWorkOrderFromCustomerOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partsServiceClient) FulfillOrderFromWorkOrder(ctx context.Context, in *FulfillOrderFromWorkOrderRequest, opts ...grpc.CallOption) (*FulfillOrderFromWorkOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FulfillOrderFromWorkOrderResponse)
	err := c.cc.Invoke(ctx, PartsService_FulfillOrderFromWorkOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartsServiceServer is the server API for PartsService service.
// All implementations must embed UnimplementedPartsServiceServer
// for forward compatibility.
type PartsServiceServer interface {
	CreatePart(context.Context, *CreatePartRequest) (*CreatePartResponse, error)
	GetPart(context.Context, *GetPartRequest) (*GetPartResponse, error)
	ListPartStock(context.Context, *ListPartStockRequest) (*ListPartStockResponse, error)
	ListParts(context.Context, *ListPartsRequest) (*ListPartsResponse, error)
	UpdatePart(context.Context, *UpdatePartRequest) (*UpdatePartResponse, error)
	DeletePart(context.Context, *DeletePartRequest) (*DeletePartResponse, error)
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error)
	GetFolder(context.Context, *GetFolderRequest) (*GetFolderResponse, error)
	ListFolders(context.Context, *ListFoldersRequest) (*ListFoldersResponse, error)
	UpdateFolder(context.Context, *UpdateFolderRequest) (*UpdateFolderResponse, error)
	DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error)
	CreateMovementDocument(context.Context, *CreateMovementDocumentRequest) (*CreateMovementDocumentResponse, error)
	GetMovementDocument(context.Context, *GetMovementDocumentRequest) (*GetMovementDocumentResponse, error)
	UpdateMovementDocument(context.Context, *UpdateMovementDocumentRequest) (*UpdateMovementDocumentResponse, error)
	ListMovementDocuments(context.Context, *ListMovementDocumentsRequest) (*ListMovementDocumentsResponse, error)
	StartMovementDocument(context.Context, *StartMovementDocumentRequest) (*StartMovementDocumentResponse, error)
	CloseMovementDocument(context.Context, *CloseMovementDocumentRequest) (*CloseMovementDocumentResponse, error)
	// Устаревший alias: закрывает документ (списание со склада).
	ConfirmMovementDocument(context.Context, *ConfirmMovementDocumentRequest) (*ConfirmMovementDocumentResponse, error)
	CancelMovementDocument(context.Context, *CancelMovementDocumentRequest) (*CancelMovementDocumentResponse, error)
	CreateProductionExtraction(context.Context, *CreateProductionExtractionRequest) (*CreateProductionExtractionResponse, error)
	ListSuppliers(context.Context, *ListSuppliersRequest) (*ListSuppliersResponse, error)
	CreateSupplierOrder(context.Context, *CreateSupplierOrderRequest) (*CreateSupplierOrderResponse, error)
	GetSupplierOrder(context.Context, *GetSupplierOrderRequest) (*GetSupplierOrderResponse, error)
	UpdateSupplierOrder(context.Context, *UpdateSupplierOrderRequest) (*UpdateSupplierOrderResponse, error)
	ListSupplierOrders(context.Context, *ListSupplierOrdersRequest) (*ListSupplierOrdersResponse, error)
	CancelSupplierOrder(context.Context, *CancelSupplierOrderRequest) (*CancelSupplierOrderResponse, error)
	CreateReceiptFromSupplierOrder(context.Context, *CreateReceiptFromSupplierOrderRequest) (*CreateReceiptFromSupplierOrderResponse, error)
	CreateCustomerOrder(context.Context, *CreateCustomerOrderRequest) (*CreateCustomerOrderResponse, error)
	GetCustomerOrder(context.Context, *GetCustomerOrderRequest) (*GetCustomerOrderResponse, error)
	UpdateCustomerOrder(context.Context, *UpdateCustomerOrderRequest) (*UpdateCustomerOrderResponse, error)
	ListCustomerOrders(context.Context, *ListCustomerOrdersRequest) (*ListCustomerOrdersResponse, error)
	CancelCustomerOrder(context.Context, *CancelCustomerOrderRequest) (*CancelCustomerOrderResponse, error)
	CreateSaleFromCustomerOrder(context.Context, *CreateSaleFromCustomerOrderRequest) (*CreateSaleFromCustomerOrderResponse, error)
	CreateWorkOrderFromSupplierOrder(context.Context, *CreateWorkOrderFromSupplierOrderRequest) (*CreateWorkOrderFromOrderResponse, error)
	CreateWorkOrderFromCustomerOrder(context.Context, *CreateWorkOrderFromCustomerOrderRequest) (*CreateWorkOrderFromOrderResponse, error)
	// Вызывается workorders-service при закрытии заказ-наряда, созданного из заказа.
	FulfillOrderFromWorkOrder(context.Context, *FulfillOrderFromWorkOrderRequest) (*FulfillOrderFromWorkOrderResponse, error)
	mustEmbedUnimplementedPartsServiceServer()
}

// UnimplementedPartsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartsServiceServer struct{}

func (UnimplementedPartsServiceServer) CreatePart(context.Context, *CreatePartRequest) (*CreatePartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePart not implemented")
}
func (UnimplementedPartsServiceServer) GetPart(context.Context, *GetPartRequest) (*GetPartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPart not implemented")
}
func (UnimplementedPartsServiceServer) ListPartStock(context.Context, *ListPartStockRequest) (*ListPartStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPartStock not implemented")
}
func (UnimplementedPartsServiceServer) ListParts(context.Context, *ListPartsRequest) (*ListPartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParts not implemented")
}
func (UnimplementedPartsServiceServer) UpdatePart(context.Context, *UpdatePartRequest) (*UpdatePartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePart not implemented")
}
func (UnimplementedPartsServiceServer) DeletePart(context.Context, *DeletePartRequest) (*DeletePartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePart not implemented")
}
func (UnimplementedPartsServiceServer) CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedPartsServiceServer) GetFolder(context.Context, *GetFolderRequest) (*GetFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFolder not implemented")
}
func (UnimplementedPartsServiceServer) ListFolders(context.Context, *ListFoldersRequest) (*ListFoldersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFolders not implemented")
}
func (UnimplementedPartsServiceServer) UpdateFolder(context.Context, *UpdateFolderRequest) (*UpdateFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFolder not implemented")
}
func (UnimplementedPartsServiceServer) DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFolder not implemented")
}
func (UnimplementedPartsServiceServer) CreateMovementDocument(context.Context, *CreateMovementDocumentRequest) (*CreateMovementDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMovementDocument not implemented")
}
func (UnimplementedPartsServiceServer) GetMovementDocument(context.Context, *GetMovementDocumentRequest) (*GetMovementDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMovementDocument not implemented")
}
func (UnimplementedPartsServiceServer) UpdateMovementDocument(context.Context, *UpdateMovementDocumentRequest) (*UpdateMovementDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMovementDocument not implemented")
}
func (UnimplementedPartsServiceServer) ListMovementDocuments(context.Context, *ListMovementDocumentsRequest) (*ListMovementDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMovementDocuments not implemented")
}
func (UnimplementedPartsServiceServer) StartMovementDocument(context.Context, *StartMovementDocumentRequest) (*StartMovementDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartMovementDocument not implemented")
}
func (UnimplementedPartsServiceServer) CloseMovementDocument(context.Context, *CloseMovementDocumentRequest) (*CloseMovementDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseMovementDocument not implemented")
}
func (UnimplementedPartsServiceServer) ConfirmMovementDocument(context.Context, *ConfirmMovementDocumentRequest) (*ConfirmMovementDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmMovementDocument not implemented")
}
func (UnimplementedPartsServiceServer) CancelMovementDocument(context.Context, *CancelMovementDocumentRequest) (*CancelMovementDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelMovementDocument not implemented")
}
func (UnimplementedPartsServiceServer) CreateProductionExtraction(context.Context, *CreateProductionExtractionRequest) (*CreateProductionExtractionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductionExtraction not implemented")
}
func (UnimplementedPartsServiceServer) ListSuppliers(context.Context, *ListSuppliersRequest) (*ListSuppliersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSuppliers not implemented")
}
func (UnimplementedPartsServiceServer) CreateSupplierOrder(context.Context, *CreateSupplierOrderRequest) (*CreateSupplierOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSupplierOrder not implemented")
}
func (UnimplementedPartsServiceServer) GetSupplierOrder(context.Context, *GetSupplierOrderRequest) (*GetSupplierOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupplierOrder not implemented")
}
func (UnimplementedPartsServiceServer) UpdateSupplierOrder(context.Context, *UpdateSupplierOrderRequest) (*UpdateSupplierOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSupplierOrder not implemented")
}
func (UnimplementedPartsServiceServer) ListSupplierOrders(context.Context, *ListSupplierOrdersRequest) (*ListSupplierOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSupplierOrders not implemented")
}
func (UnimplementedPartsServiceServer) CancelSupplierOrder(context.Context, *CancelSupplierOrderRequest) (*CancelSupplierOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSupplierOrder not implemented")
}
func (UnimplementedPartsServiceServer) CreateReceiptFromSupplierOrder(context.Context, *CreateReceiptFromSupplierOrderRequest) (*CreateReceiptFromSupplierOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReceiptFromSupplierOrder not implemented")
}
func (UnimplementedPartsServiceServer) CreateCustomerOrder(context.Context, *CreateCustomerOrderRequest) (*CreateCustomerOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCustomerOrder not implemented")
}
func (UnimplementedPartsServiceServer) GetCustomerOrder(context.Context, *GetCustomerOrderRequest) (*GetCustomerOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomerOrder not implemented")
}
func (UnimplementedPartsServiceServer) UpdateCustomerOrder(context.Context, *UpdateCustomerOrderRequest) (*UpdateCustomerOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCustomerOrder not implemented")
}
func (UnimplementedPartsServiceServer) ListCustomerOrders(context.Context, *ListCustomerOrdersRequest) (*ListCustomerOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCustomerOrders not implemented")
}
func (UnimplementedPartsServiceServer) CancelCustomerOrder(context.Context, *CancelCustomerOrderRequest) (*CancelCustomerOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelCustomerOrder not implemented")
}
func (UnimplementedPartsServiceServer) CreateSaleFromCustomerOrder(context.Context, *CreateSaleFromCustomerOrderRequest) (*CreateSaleFromCustomerOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSaleFromCustomerOrder not implemented")
}
func (UnimplementedPartsServiceServer) CreateWorkOrderFromSupplierOrder(context.Context, *CreateWorkOrderFromSupplierOrderRequest) (*CreateWorkOrderFromOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkOrderFromSupplierOrder not implemented")
}
func (UnimplementedPartsServiceServer) CreateWorkOrderFromCustomerOrder(context.Context, *CreateWorkOrderFromCustomerOrderRequest) (*CreateWorkOrderFromOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkOrderFromCustomerOrder not implemented")
}
func (UnimplementedPartsServiceServer) FulfillOrderFromWorkOrder(context.Context, *FulfillOrderFromWorkOrderRequest) (*FulfillOrderFromWorkOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FulfillOrderFromWorkOrder not implemented")
}
func (UnimplementedPartsServiceServer) mustEmbedUnimplementedPartsServiceServer() {}
func (UnimplementedPartsServiceServer) testEmbeddedByValue()                      {}

// UnsafePartsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartsServiceServer will
// result in compilation errors.
type UnsafePartsServiceServer interface {
	mustEmbedUnimplementedPartsServiceServer()
}

func RegisterPartsServiceServer(s grpc.ServiceRegistrar, srv PartsServiceServer) {
	// If the following call panics, it indicates UnimplementedPartsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartsService_ServiceDesc, srv)
}

func _PartsService_CreatePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreatePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreatePart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreatePart(ctx, req.(*CreatePartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_GetPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).GetPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_GetPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).GetPart(ctx, req.(*GetPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_ListPartStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).ListPartStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_ListPartStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).ListPartStock(ctx, req.(*ListPartStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_ListParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).ListParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_ListParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).ListParts(ctx, req.(*ListPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_UpdatePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).UpdatePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_UpdatePart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).UpdatePart(ctx, req.(*UpdatePartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_DeletePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).DeletePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_DeletePart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).DeletePart(ctx, req.(*DeletePartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_GetFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).GetFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_GetFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).GetFolder(ctx, req.(*GetFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_ListFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).ListFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_ListFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).ListFolders(ctx, req.(*ListFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_UpdateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).UpdateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_UpdateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).UpdateFolder(ctx, req.(*UpdateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_DeleteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).DeleteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_DeleteFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).DeleteFolder(ctx, req.(*DeleteFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateMovementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMovementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateMovementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateMovementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateMovementDocument(ctx, req.(*CreateMovementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_GetMovementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).GetMovementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_GetMovementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).GetMovementDocument(ctx, req.(*GetMovementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_UpdateMovementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMovementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).UpdateMovementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_UpdateMovementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).UpdateMovementDocument(ctx, req.(*UpdateMovementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_ListMovementDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMovementDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).ListMovementDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_ListMovementDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).ListMovementDocuments(ctx, req.(*ListMovementDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_StartMovementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMovementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).StartMovementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_StartMovementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).StartMovementDocument(ctx, req.(*StartMovementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CloseMovementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseMovementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CloseMovementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CloseMovementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CloseMovementDocument(ctx, req.(*CloseMovementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_ConfirmMovementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmMovementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).ConfirmMovementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_ConfirmMovementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).ConfirmMovementDocument(ctx, req.(*ConfirmMovementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CancelMovementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMovementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CancelMovementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CancelMovementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CancelMovementDocument(ctx, req.(*CancelMovementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateProductionExtraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductionExtractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateProductionExtraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateProductionExtraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateProductionExtraction(ctx, req.(*CreateProductionExtractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_ListSuppliers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSuppliersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).ListSuppliers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_ListSuppliers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).ListSuppliers(ctx, req.(*ListSuppliersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateSupplierOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateSupplierOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateSupplierOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateSupplierOrder(ctx, req.(*CreateSupplierOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_GetSupplierOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupplierOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).GetSupplierOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_GetSupplierOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).GetSupplierOrder(ctx, req.(*GetSupplierOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_UpdateSupplierOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupplierOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).UpdateSupplierOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_UpdateSupplierOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).UpdateSupplierOrder(ctx, req.(*UpdateSupplierOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_ListSupplierOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupplierOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).ListSupplierOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_ListSupplierOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).ListSupplierOrders(ctx, req.(*ListSupplierOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CancelSupplierOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSupplierOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CancelSupplierOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CancelSupplierOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CancelSupplierOrder(ctx, req.(*CancelSupplierOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateReceiptFromSupplierOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceiptFromSupplierOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateReceiptFromSupplierOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateReceiptFromSupplierOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateReceiptFromSupplierOrder(ctx, req.(*CreateReceiptFromSupplierOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateCustomerOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateCustomerOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateCustomerOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateCustomerOrder(ctx, req.(*CreateCustomerOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_GetCustomerOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).GetCustomerOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_GetCustomerOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).GetCustomerOrder(ctx, req.(*GetCustomerOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_UpdateCustomerOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).UpdateCustomerOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_UpdateCustomerOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).UpdateCustomerOrder(ctx, req.(*UpdateCustomerOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_ListCustomerOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomerOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).ListCustomerOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_ListCustomerOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).ListCustomerOrders(ctx, req.(*ListCustomerOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CancelCustomerOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCustomerOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CancelCustomerOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CancelCustomerOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CancelCustomerOrder(ctx, req.(*CancelCustomerOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateSaleFromCustomerOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSaleFromCustomerOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateSaleFromCustomerOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateSaleFromCustomerOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateSaleFromCustomerOrder(ctx, req.(*CreateSaleFromCustomerOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateWorkOrderFromSupplierOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkOrderFromSupplierOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateWorkOrderFromSupplierOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateWorkOrderFromSupplierOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateWorkOrderFromSupplierOrder(ctx, req.(*CreateWorkOrderFromSupplierOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_CreateWorkOrderFromCustomerOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkOrderFromCustomerOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).CreateWorkOrderFromCustomerOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_CreateWorkOrderFromCustomerOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).CreateWorkOrderFromCustomerOrder(ctx, req.(*CreateWorkOrderFromCustomerOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartsService_FulfillOrderFromWorkOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FulfillOrderFromWorkOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartsServiceServer).FulfillOrderFromWorkOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartsService_FulfillOrderFromWorkOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartsServiceServer).FulfillOrderFromWorkOrder(ctx, req.(*FulfillOrderFromWorkOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartsService_ServiceDesc is the grpc.ServiceDesc for PartsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parts.v1.PartsService",
	HandlerType: (*PartsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePart",
			Handler:    _PartsService_CreatePart_Handler,
		},
		{
			MethodName: "GetPart",
			Handler:    _PartsService_GetPart_Handler,
		},
		{
			MethodName: "ListPartStock",
			Handler:    _PartsService_ListPartStock_Handler,
		},
		{
			MethodName: "ListParts",
			Handler:    _PartsService_ListParts_Handler,
		},
		{
			MethodName: "UpdatePart",
			Handler:    _PartsService_UpdatePart_Handler,
		},
		{
			MethodName: "DeletePart",
			Handler:    _PartsService_DeletePart_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _PartsService_CreateFolder_Handler,
		},
		{
			MethodName: "GetFolder",
			Handler:    _PartsService_GetFolder_Handler,
		},
		{
			MethodName: "ListFolders",
			Handler:    _PartsService_ListFolders_Handler,
		},
		{
			MethodName: "UpdateFolder",
			Handler:    _PartsService_UpdateFolder_Handler,
		},
		{
			MethodName: "DeleteFolder",
			Handler:    _PartsService_DeleteFolder_Handler,
		},
		{
			MethodName: "CreateMovementDocument",
			Handler:    _PartsService_CreateMovementDocument_Handler,
		},
		{
			MethodName: "GetMovementDocument",
			Handler:    _PartsService_GetMovementDocument_Handler,
		},
		{
			MethodName: "UpdateMovementDocument",
			Handler:    _PartsService_UpdateMovementDocument_Handler,
		},
		{
			MethodName: "ListMovementDocuments",
			Handler:    _PartsService_ListMovementDocuments_Handler,
		},
		{
			MethodName: "StartMovementDocument",
			Handler:    _PartsService_StartMovementDocument_Handler,
		},
		{
			MethodName: "CloseMovementDocument",
			Handler:    _PartsService_CloseMovementDocument_Handler,
		},
		{
			MethodName: "ConfirmMovementDocument",
			Handler:    _PartsService_ConfirmMovementDocument_Handler,
		},
		{
			MethodName: "CancelMovementDocument",
			Handler:    _PartsService_CancelMovementDocument_Handler,
		},
		{
			MethodName: "CreateProductionExtraction",
			Handler:    _PartsService_CreateProductionExtraction_Handler,
		},
		{
			MethodName: "ListSuppliers",
			Handler:    _PartsService_ListSuppliers_Handler,
		},
		{
			MethodName: "CreateSupplierOrder",
			Handler:    _PartsService_CreateSupplierOrder_Handler,
		},
		{
			MethodName: "GetSupplierOrder",
			Handler:    _PartsService_GetSupplierOrder_Handler,
		},
		{
			MethodName: "UpdateSupplierOrder",
			Handler:    _PartsService_UpdateSupplierOrder_Handler,
		},
		{
			MethodName: "ListSupplierOrders",
			Handler:    _PartsService_ListSupplierOrders_Handler,
		},
		{
			MethodName: "CancelSupplierOrder",
			Handler:    _PartsService_CancelSupplierOrder_Handler,
		},
		{
			MethodName: "CreateReceiptFromSupplierOrder",
			Handler:    _PartsService_CreateReceiptFromSupplierOrder_Handler,
		},
		{
			MethodName: "CreateCustomerOrder",
			Handler:    _PartsService_CreateCustomerOrder_Handler,
		},
		{
			MethodName: "GetCustomerOrder",
			Handler:    _PartsService_GetCustomerOrder_Handler,
		},
		{
			MethodName: "UpdateCustomerOrder",
			Handler:    _PartsService_UpdateCustomerOrder_Handler,
		},
		{
			MethodName: "ListCustomerOrders",
			Handler:    _PartsService_ListCustomerOrders_Handler,
		},
		{
			MethodName: "CancelCustomerOrder",
			Handler:    _PartsService_CancelCustomerOrder_Handler,
		},
		{
			MethodName: "CreateSaleFromCustomerOrder",
			Handler:    _PartsService_CreateSaleFromCustomerOrder_Handler,
		},
		{
			MethodName: "CreateWorkOrderFromSupplierOrder",
			Handler:    _PartsService_CreateWorkOrderFromSupplierOrder_Handler,
		},
		{
			MethodName: "CreateWorkOrderFromCustomerOrder",
			Handler:    _PartsService_CreateWorkOrderFromCustomerOrder_Handler,
		},
		{
			MethodName: "FulfillOrderFromWorkOrder",
			Handler:    _PartsService_FulfillOrderFromWorkOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parts/v1/parts.proto",
}
