// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: clientauth/v1/clientauth_session.proto

package clientauthv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_clientauth_v1_clientauth_session_proto protoreflect.FileDescriptor

const file_clientauth_v1_clientauth_session_proto_rawDesc = "" +
	"\n" +
	"&clientauth/v1/clientauth_session.proto\x12\rclientauth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1eclientauth/v1/clientauth.proto2x\n" +
	"\x18ClientAuthSessionService\x12\\\n" +
	"\bValidate\x12\x1e.clientauth.v1.ValidateRequest\x1a\x1f.clientauth.v1.ValidateResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/api/meB<Z:github.com/dealer/dealer/pkg/pb/clientauth/v1;clientauthv1b\x06proto3"

var file_clientauth_v1_clientauth_session_proto_goTypes = []any{
	(*ValidateRequest)(nil),  // 0: clientauth.v1.ValidateRequest
	(*ValidateResponse)(nil), // 1: clientauth.v1.ValidateResponse
}
var file_clientauth_v1_clientauth_session_proto_depIdxs = []int32{
	0, // 0: clientauth.v1.ClientAuthSessionService.Validate:input_type -> clientauth.v1.ValidateRequest
	1, // 1: clientauth.v1.ClientAuthSessionService.Validate:output_type -> clientauth.v1.ValidateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientauth_v1_clientauth_session_proto_init() }
func file_clientauth_v1_clientauth_session_proto_init() {
	if File_clientauth_v1_clientauth_session_proto != nil {
		return
	}
	file_clientauth_v1_clientauth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clientauth_v1_clientauth_session_proto_rawDesc), len(file_clientauth_v1_clientauth_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientauth_v1_clientauth_session_proto_goTypes,
		DependencyIndexes: file_clientauth_v1_clientauth_session_proto_depIdxs,
	}.Build()
	File_clientauth_v1_clientauth_session_proto = out.File
	file_clientauth_v1_clientauth_session_proto_goTypes = nil
	file_clientauth_v1_clientauth_session_proto_depIdxs = nil
}
