apiVersion: apps/v1
kind: Deployment
metadata:
  name: deals-service
  namespace: dealer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deals-service
  template:
    metadata:
      labels:
        app: deals-service
    spec:
      containers:
        - name: deals-service
          image: __IMG_DEALS__
          imagePullPolicy: __PULL_POLICY__
          ports:
            - containerPort: 50054
            - containerPort: 8083
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: DEALS_GRPC_PORT
              value: "50054"
            - name: DEALS_HTTP_PORT
              value: "8083"
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: dealer-db
                  key: POSTGRES_DSN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dealer-app-secrets
                  key: JWT_SECRET