// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: statistics/employee/v1/employee_stats.proto

/*
Package employeestatsv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package employeestatsv1

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_EmployeeStatisticsService_GetOverview_0(ctx context.Context, marshaler runtime.Marshaler, client EmployeeStatisticsServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetOverviewRequest
		metadata runtime.ServerMetadata
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.GetOverview(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_EmployeeStatisticsService_GetOverview_0(ctx context.Context, marshaler runtime.Marshaler, server EmployeeStatisticsServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetOverviewRequest
		metadata runtime.ServerMetadata
	)
	msg, err := server.GetOverview(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterEmployeeStatisticsServiceHandlerServer registers the http handlers for service EmployeeStatisticsService to "mux".
// UnaryRPC     :call EmployeeStatisticsServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterEmployeeStatisticsServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterEmployeeStatisticsServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server EmployeeStatisticsServiceServer) error {
	mux.Handle(http.MethodGet, pattern_EmployeeStatisticsService_GetOverview_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/statistics.employee.v1.EmployeeStatisticsService/GetOverview", runtime.WithHTTPPathPattern("/api/stats/employee/overview"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_EmployeeStatisticsService_GetOverview_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_EmployeeStatisticsService_GetOverview_0(annotatedContext, mux, outboundMarshaler, w, req, response_EmployeeStatisticsService_GetOverview_0{resp.(*GetOverviewResponse)}, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterEmployeeStatisticsServiceHandlerFromEndpoint is same as RegisterEmployeeStatisticsServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterEmployeeStatisticsServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterEmployeeStatisticsServiceHandler(ctx, mux, conn)
}

// RegisterEmployeeStatisticsServiceHandler registers the http handlers for service EmployeeStatisticsService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterEmployeeStatisticsServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterEmployeeStatisticsServiceHandlerClient(ctx, mux, NewEmployeeStatisticsServiceClient(conn))
}

// RegisterEmployeeStatisticsServiceHandlerClient registers the http handlers for service EmployeeStatisticsService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "EmployeeStatisticsServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "EmployeeStatisticsServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "EmployeeStatisticsServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterEmployeeStatisticsServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client EmployeeStatisticsServiceClient) error {
	mux.Handle(http.MethodGet, pattern_EmployeeStatisticsService_GetOverview_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/statistics.employee.v1.EmployeeStatisticsService/GetOverview", runtime.WithHTTPPathPattern("/api/stats/employee/overview"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_EmployeeStatisticsService_GetOverview_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_EmployeeStatisticsService_GetOverview_0(annotatedContext, mux, outboundMarshaler, w, req, response_EmployeeStatisticsService_GetOverview_0{resp.(*GetOverviewResponse)}, mux.GetForwardResponseOptions()...)
	})
	return nil
}

type response_EmployeeStatisticsService_GetOverview_0 struct {
	*GetOverviewResponse
}

func (m response_EmployeeStatisticsService_GetOverview_0) XXX_ResponseBody() interface{} {
	response := m.GetOverviewResponse
	return response.Overview
}

var (
	pattern_EmployeeStatisticsService_GetOverview_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"api", "stats", "employee", "overview"}, ""))
)

var (
	forward_EmployeeStatisticsService_GetOverview_0 = runtime.ForwardResponseMessage
)
