apiVersion: v1
kind: Service
metadata:
  name: employee-statistics-service
  namespace: dealer
spec:
  selector:
    app: employee-statistics-service
  ports:
    - name: grpc
      port: 50061
      targetPort: 50061
    - name: http
      port: 8094
      targetPort: 8094
