apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: dealer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: __IMG_AUTH__
          imagePullPolicy: __PULL_POLICY__
          ports:
            - containerPort: 50051
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: AUTH_GRPC_PORT
              value: "50051"
            - name: AUTH_HTTP_PORT
              value: "8080"
            - name: STATIC_DIR
              value: "/app/web"
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: dealer-db
                  key: POSTGRES_DSN
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKERS
              value: "kafka:29092"
            - name: KAFKA_TOPIC_AUTH_EVENTS
              value: "auth.events"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dealer-app-secrets
                  key: JWT_SECRET
            - name: CUSTOMERS_SERVICE_URL
              value: "http://customers-service.dealer.svc.cluster.local:8081"
            - name: VEHICLES_SERVICE_URL
              value: "http://vehicles-service.dealer.svc.cluster.local:8082"
            - name: DEALS_SERVICE_URL
              value: "http://deals-service.dealer.svc.cluster.local:8083"
            - name: PARTS_SERVICE_URL
              value: "http://parts-service.dealer.svc.cluster.local:8084"
            - name: BRANDS_SERVICE_URL
              value: "http://brands-service.dealer.svc.cluster.local:8085"
            - name: DEALER_POINTS_SERVICE_URL
              value: "http://dealer-points-service.dealer.svc.cluster.local:8086"

          