apiVersion: v1
kind: Service
metadata:
  name: client-public-gateway-service
  namespace: dealer
spec:
  type: NodePort
  selector:
    app: client-public-gateway-service
  ports:
    - name: http
      port: 8091
      targetPort: 8091
