apiVersion: v1
kind: Service
metadata:
  name: client-statistics-service
  namespace: dealer
spec:
  selector:
    app: client-statistics-service
  ports:
    - name: grpc
      port: 50062
      targetPort: 50062
    - name: http
      port: 8095
      targetPort: 8095
