apiVersion: v1
kind: Service
metadata:
  name: client-reviews-service
  namespace: dealer
spec:
  selector:
    app: client-reviews-service
  ports:
    - name: grpc
      port: 50060
      targetPort: 50060
    - name: http
      port: 8089
      targetPort: 8089
