// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: clients/v1/account.proto

package clientsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientAccountService_AddVehicle_FullMethodName     = "/clients.v1.ClientAccountService/AddVehicle"
	ClientAccountService_ListMyVehicles_FullMethodName = "/clients.v1.ClientAccountService/ListMyVehicles"
	ClientAccountService_GetProfile_FullMethodName     = "/clients.v1.ClientAccountService/GetProfile"
)

// ClientAccountServiceClient is the client API for ClientAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Личный кабинет клиента (client-protected-gateway).
type ClientAccountServiceClient interface {
	AddVehicle(ctx context.Context, in *AddVehicleRequest, opts ...grpc.CallOption) (*AddVehicleResponse, error)
	ListMyVehicles(ctx context.Context, in *ListMyVehiclesRequest, opts ...grpc.CallOption) (*ListMyVehiclesResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
}

type clientAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientAccountServiceClient(cc grpc.ClientConnInterface) ClientAccountServiceClient {
	return &clientAccountServiceClient{cc}
}

func (c *clientAccountServiceClient) AddVehicle(ctx context.Context, in *AddVehicleRequest, opts ...grpc.CallOption) (*AddVehicleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVehicleResponse)
	err := c.cc.Invoke(ctx, ClientAccountService_AddVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAccountServiceClient) ListMyVehicles(ctx context.Context, in *ListMyVehiclesRequest, opts ...grpc.CallOption) (*ListMyVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyVehiclesResponse)
	err := c.cc.Invoke(ctx, ClientAccountService_ListMyVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAccountServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, ClientAccountService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientAccountServiceServer is the server API for ClientAccountService service.
// All implementations must embed UnimplementedClientAccountServiceServer
// for forward compatibility.
//
// Личный кабинет клиента (client-protected-gateway).
type ClientAccountServiceServer interface {
	AddVehicle(context.Context, *AddVehicleRequest) (*AddVehicleResponse, error)
	ListMyVehicles(context.Context, *ListMyVehiclesRequest) (*ListMyVehiclesResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	mustEmbedUnimplementedClientAccountServiceServer()
}

// UnimplementedClientAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientAccountServiceServer struct{}

func (UnimplementedClientAccountServiceServer) AddVehicle(context.Context, *AddVehicleRequest) (*AddVehicleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVehicle not implemented")
}
func (UnimplementedClientAccountServiceServer) ListMyVehicles(context.Context, *ListMyVehiclesRequest) (*ListMyVehiclesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyVehicles not implemented")
}
func (UnimplementedClientAccountServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedClientAccountServiceServer) mustEmbedUnimplementedClientAccountServiceServer() {}
func (UnimplementedClientAccountServiceServer) testEmbeddedByValue()                              {}

// UnsafeClientAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientAccountServiceServer will
// result in compilation errors.
type UnsafeClientAccountServiceServer interface {
	mustEmbedUnimplementedClientAccountServiceServer()
}

func RegisterClientAccountServiceServer(s grpc.ServiceRegistrar, srv ClientAccountServiceServer) {
	// If the following call panics, it indicates UnimplementedClientAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientAccountService_ServiceDesc, srv)
}

func _ClientAccountService_AddVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAccountServiceServer).AddVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAccountService_AddVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAccountServiceServer).AddVehicle(ctx, req.(*AddVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAccountService_ListMyVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAccountServiceServer).ListMyVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAccountService_ListMyVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAccountServiceServer).ListMyVehicles(ctx, req.(*ListMyVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAccountService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAccountServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAccountService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAccountServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientAccountService_ServiceDesc is the grpc.ServiceDesc for ClientAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clients.v1.ClientAccountService",
	HandlerType: (*ClientAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVehicle",
			Handler:    _ClientAccountService_AddVehicle_Handler,
		},
		{
			MethodName: "ListMyVehicles",
			Handler:    _ClientAccountService_ListMyVehicles_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _ClientAccountService_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients/v1/account.proto",
}
